product_importer.dodaj:
  path: '/dodaj'
  defaults:
    _form: 'Drupal\product_importer\Form\ProductImportForm'
    _title: 'Import'
  requirements:
    _permission: 'Import form'

product_importer.order:
  path: '/order/{orderID}'
  defaults:
    _controller: 'Drupal\product_importer\Controller\OrderController::order'
    _title: 'Order'
  requirements:
    _permission: 'access content'
